package net.breezeware.dynamo.notification.push.bff.dto;

import java.util.UUID;

import lombok.Data;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;

/**
 * User device map dto.
 */
@Data
public class UserDeviceMapDto {

    /**
     * Unique UUID of the Dynamo-user.
     */
    @Schema(example = "a3e11faf-bc28-4d2c-b313-d2d176875ffa", description = "Unique UUID of the Dynamo-user")
    private UUID userId;

    /**
     * Cloud messaging platform type.
     */
    @Schema(example = "APNS", description = "Cloud messaging type.")
    @NotBlank(message = "Messaging Platform type is missing or blank")
    private String platformType;

    /**
     * Device token/id generated by the MDM server after successful registration of
     * the device.
     */
    @Schema(example = "1b947aacfaafc3c10729dcac097c90e466d1906c4926ea8546cce02ff3b73c86",
            description = "Device token/id generated by the MDM server after successful registration of the device.")
    @NotBlank(message = "Device token/Id is missing or blank")
    private String deviceToken;
}
